spring:
  application:
    name: ${vcap.application.name}
  cloud:
    services:
      registrationMethod: route

feign:
  hystrix:
    enabled: true

---
spring:
  profiles: dev

security:
  basic:
    enabled: false
